/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElDropdown: typeof import('element-plus/lib')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/lib')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/lib')['ElDropdownMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
